# -*- coding: utf-8 -*-
"""Python Calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vHf38E1lBw3wP0LahWw9yLmBYMo_ck4J
"""

# Display the operation menu to the user
print(" WHAT YOU WANT TO DO ?")
print(" 1. ADDITION ")
print(" 2. SUBTRACTION ")
print(" 3. MULTIPLICATION ")
print(" 4. DIVIDE ")

# Get the menu choice from the user and convert it to an integer
choice = int(input(" ENTER YOUR CHOICE (1-4) : "))

# Get two numbers from the user and convert them to decimals (floats)
num1 = float(input(" ENTER NUMBER 1 : "))
num2 = float(input(" ENTER NUMBER 2 : "))

# Perform Addition if the user chose option 1
if choice == 1:
    print("ADDITION : ", num1 + num2)

# Perform Subtraction if the user chose option 2
elif choice == 2:
    print("SUBTRACTION : ", num1 - num2)

# Perform Multiplication if the user chose option 3
elif choice == 3:
    print("MULTIPLICATION : ", num1 * num2)

# Perform Division if the user chose option 4
elif choice == 4:
    # Check if the second number is zero to avoid a division-by-zero crash
    if num2 != 0:
        print("DIVISION:", num1 / num2)
    else:
        print("CANT DIVIDE BY 0:")

# Handle any choice outside the 1-4 range
else:
    print("INVALID SYNTAX :")